package com.example.benjo.bil_app_kotlin.utils

class Constants {
    companion object {
        const val TITLE_TAB_1 = "Fordonsdata"
        const val TITLE_TAB_2 = "Teknisk data"
        const val TITLE_TAB_3 = "Historik"



        /* API OBJECTS */
        const val MAKE = "make"
        const val MODEL = "model"
        const val STATUS = "status"
        const val COLOR = "color"
        const val TYPE = "type"
        const val VEH_YEAR = "vehicle_year"
        const val MOD_YEAR = "model_year"
        const val HP_1 = "power_hp_1"
        const val HP_2 = "power_hp_2"
        const val HP_3 = "power_hp_3"

        const val KW_1 = "power_kw_1"
        const val KW_2 = "power_kw_2"
        const val KW_3 = "power_kw_3"
        const val CYL_VOL = "cylinder_volume"
        const val TOP_SPEED = "top_speed"
        const val FUEL_1 = "fuel_1"
        const val FUEL_2 = "fuel_2"
        const val CONSUMPTION_1 = "consumption_1"
        const val CONSUMPTION_2 = "consumption_2"
        const val CONSUMPTION_3 = "consumption_3"
        const val CO2_1 = "co2_1"
        const val CO2_2 = "co2_2"
        const val CO2_3 = "co2_3"
        const val TRANSMISSION = "transmission"
        const val FOUR_WHEEL_DRIVE = "four_wheel_drive"
        const val SOUND_LVL_1 = "sound_level_1"
        const val SOUND_LVL_2 = "sound_level_2"
        const val SOUND_LVL_3 = "sound_level_3"
        const val NO_PASSENGERS = "number_of_passengers"
        const val PASSENGER_AB = "passenger_airbag"
        const val HITCH = "hitch"
        const val HITCH_2 = "hitch_2"
        const val CHASSI_CODE_1 = "chassi_code_1"
        const val CHASSI_CODE_2 = "chassi_code_2"
        const val CHASSI = "chassi"
        const val LENGTH = "length"
        const val WIDTH = "width"
        const val HEIGHT = "height"
        const val KERB_WEIGHT = "kerb_weight"
        const val TOTAL_WEIGHT = "total_weight"
        const val LOAD_WEIGHT = "load_weight"
        const val TRAILER_WEIGHT = "trailer_weight"
        const val UNBR_TRAILER_WEIGHT = "unbraked_trailer_weight"
        const val TRAILER_WEIGHT_B = "trailer_weight_b"
        const val TRAILER_WEIGHT_BE = "trailer_weight_be"
        const val CARR_WEIGHT = "carriage_weight"
        const val TIRE_FRONT = "tire_front"
        const val TIRE_BACK = "tire_back"
        const val RIM_FRONT = "rim_front"
        const val RIM_BACK = "rim_back"
        const val AXEL_WIDTH = "axel_width"
        const val CATEGORY = "category"
        const val EEG = "eeg"
        const val NOX_1 = "nox_1"
        const val NOX_2 = "nox_2"
        const val NOX_3 = "nox_3"
        const val THC_NOX_1 = "thc_nox_1"
        const val THC_NOX_2 = "thc_nox_2"
        const val THC_NOX_3 = "thc_nox_3"
        const val ECO_CLASS = "eco_class"
        const val EMISS_CLASS = "emission_class"
        const val EURO_NCAP = "euro_ncap"

    }
}