package com.example.benjo.bil_app_kotlin.utils

class ExplanationConstants {
    companion object {

        /* --------------- Vehicle types --------------- */
        const val VEHICLE_BUSS      = "Buss"
        const val VEHICLE_PB        = "Personbil"
        const val VEHICLE_LB        = "Lastbil"
        const val VEHICLE_MC        = "Motorcykel"
        const val VEHICLE_MOPED     = "Moped"
        const val VEHICLE_MRED      = "Motorredskap"
        const val VEHICLE_SLAP      = "Släp"
        const val VEHICLE_TGHJUL    = "Terränghjuling"
        const val VEHICLE_TGSK      = "Terrängskoter"
        const val VEHICLE_TGSL      = "Terrängsläp"
        const val VEHICLE_TGSNO     = "Snöskoter"
        const val VEHICLE_TGV       = "Terrängvagn"
        const val VEHICLE_TR        = "Traktor"
        /* --------------------------------------------- */


        /* --------------- Status types --------------- */
        const val STATUS_1 = "Avställd"
        const val STATUS_2 = "I trafik"
        const val STATUS_3 = "Avregistrerad"
        const val STATUS_4 = "Aldrig i trafik"
        /* --------------------------------------------- */


        /* --------------- Fuel types --------------- */
        const val BENSIN     = "Bensin"
        const val DIESEL     = "Diesel"
        const val EL         = "El"
        const val FOTOGEN    = "Fotogen"
        const val GENGAS     = "Gengas"
        const val ETANOL     = "Etanol"
        const val MOTORGAS   = "Motorgas"
        const val METANGAS   = "Metangas"
        const val VATGAS     = "Vätgas"
        const val ANNAT      = "Annat"
        const val BIODIESEL  = "Biodiesel"
        /* --------------------------------------------- */


        /* --------------- Transmission types --------------- */
        const val MANUELL           = "Manuell"
        const val AUTOMAT           = "Automat"
        const val MANUELL_TILLSATS  = "Manuell med tillsats"
        const val AUTOMAT_TILLSATS  = "Automat med tillsats"
        const val VARIOMATIC        = "Variomatic"
        /* --------------------------------------------- */


        /* --------------- Emission types --------------- */
        const val EMISSION_EURO_4         = "Euro4"
        const val EMISSION_EURO_5         = "Euro5"
        const val EMISSION_EURO_6         = "Euro6"
        const val EMISSION_EL             = "El"
        const val EMISSION_EL_HYBDRID     = "Elhybryd"
        const val EMISSION_LADD_HYBDRID   = "Laddhybrid"
        const val EMISSION_EEV            = "EEV"
        /* --------------------------------------------- */


        /* --------------- Chassi types --------------- */ // TODO start från 0 ist för 1
        const val CHASSI_CODE_1           = "Taxi"
        const val CHASSI_CODE_2           = "Rullstolsanpassat fordon"
        const val CHASSI_CODE_3           = "Tvåvånings låggolvsbuss"
        const val CHASSI_CODE_4           = "Cabriolet"
        const val CHASSI_CODE_5           = "Bärgningsfordon"
        const val CHASSI_CODE_6           = "Envånings låggolvsbuss"
        const val CHASSI_CODE_7           = "Motviktstruck"
        const val CHASSI_CODE_8           = ""
        const val CHASSI_CODE_9           = ""
        const val CHASSI_CODE_10           = ""
        const val CHASSI_CODE_11           = ""
        const val CHASSI_CODE_12           = ""
        const val CHASSI_CODE_13           = ""
        const val CHASSI_CODE_14           = ""
        const val CHASSI_CODE_15           = ""
        const val CHASSI_CODE_16           = ""
        const val CHASSI_CODE_17           = ""
        const val CHASSI_CODE_18           = ""
        const val CHASSI_CODE_19           = ""
        const val CHASSI_CODE_20           = ""
        const val CHASSI_CODE_21           = ""
        const val CHASSI_CODE_22           = ""
        const val CHASSI_CODE_23           = ""
        const val CHASSI_CODE_24          = ""
        const val CHASSI_CODE_25           = ""
        const val CHASSI_CODE_26           = ""
        const val CHASSI_CODE_27           = ""
        const val CHASSI_CODE_28           = ""
        const val CHASSI_CODE_29           = ""
        const val CHASSI_CODE_30           = ""
        const val CHASSI_CODE_31           = ""
        const val CHASSI_CODE_32           = ""
        const val CHASSI_CODE_33           = ""
        const val CHASSI_CODE_34           = ""
        const val CHASSI_CODE_35           = ""
        const val CHASSI_CODE_36           = ""
        const val CHASSI_CODE_37           = ""
        const val CHASSI_CODE_38           = ""
        const val CHASSI_CODE_39           = ""

        const val CHASSI_CODE_40           = ""
        const val CHASSI_CODE_41           = ""
        const val CHASSI_CODE_42          = ""
        const val CHASSI_CODE_43           = ""
        const val CHASSI_CODE_44           = ""
        const val CHASSI_CODE_45           = ""
        const val CHASSI_CODE_46          = ""
        const val CHASSI_CODE_47           = ""
        const val CHASSI_CODE_48           = ""
        const val CHASSI_CODE_49           = ""
        const val CHASSI_CODE_50           = ""
        const val CHASSI_CODE_51           = ""
        const val CHASSI_CODE_52           = ""
        const val CHASSI_CODE_53           = ""
        const val CHASSI_CODE_54           = ""
        const val CHASSI_CODE_55           = ""
        const val CHASSI_CODE_56           = ""
        const val CHASSI_CODE_57           = ""
        const val CHASSI_CODE_58           = ""
        const val CHASSI_CODE_59           = ""
        const val CHASSI_CODE_60           = ""
        const val CHASSI_CODE_61           = ""
        const val CHASSI_CODE_62           = ""
        const val CHASSI_CODE_63          = ""
        const val CHASSI_CODE_64           = ""
        const val CHASSI_CODE_65           = ""
        const val CHASSI_CODE_66           = ""
        const val CHASSI_CODE_67           = ""
        const val CHASSI_CODE_68           = ""
        const val CHASSI_CODE_69           = ""
        const val CHASSI_CODE_70           = ""
        const val CHASSI_CODE_71           = ""
        const val CHASSI_CODE_72           = ""
        const val CHASSI_CODE_73           = ""
        const val CHASSI_CODE_74           = ""
        const val CHASSI_CODE_75           = ""
        const val CHASSI_CODE_76           = ""
        const val CHASSI_CODE_77           = ""
        const val CHASSI_CODE_78           = ""

        const val CHASSI_CODE_79           = ""
        const val CHASSI_CODE_80           = ""
        const val CHASSI_CODE_81          = ""
        const val CHASSI_CODE_82           = ""
        const val CHASSI_CODE_83           = ""
        const val CHASSI_CODE_84           = ""
        const val CHASSI_CODE_85          = ""
        const val CHASSI_CODE_86           = ""
        const val CHASSI_CODE_87           = ""
        const val CHASSI_CODE_88           = ""
        const val CHASSI_CODE_89           = ""
        const val CHASSI_CODE_90           = ""
        const val CHASSI_CODE_91           = ""
        const val CHASSI_CODE_92           = ""
        const val CHASSI_CODE_93           = ""
        const val CHASSI_CODE_94           = ""
        const val CHASSI_CODE_95           = ""
        const val CHASSI_CODE_96           = ""
        const val CHASSI_CODE_97           = ""
        const val CHASSI_CODE_98           = ""
        const val CHASSI_CODE_99           = ""
        const val CHASSI_CODE_100           = ""
        const val CHASSI_CODE_101          = ""
        const val CHASSI_CODE_102          = ""
        const val CHASSI_CODE_103           = ""
        const val CHASSI_CODE_104           = ""
        const val CHASSI_CODE_105           = ""
        const val CHASSI_CODE_106          = ""
        const val CHASSI_CODE_107           = ""
        const val CHASSI_CODE_108           = ""
        const val CHASSI_CODE_109           = ""
        const val CHASSI_CODE_110           = ""
        const val CHASSI_CODE_111           = ""
        const val CHASSI_CODE_112           = ""
        const val CHASSI_CODE_113           = ""
        const val CHASSI_CODE_114           = ""
        const val CHASSI_CODE_115           = ""
        const val CHASSI_CODE_116           = ""
        const val CHASSI_CODE_117           = ""

        /* --------------------------------------------- */


    }
}